backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# Uncomment below to enable drafts
# publish_mode: editorial_workflow

media_folder: "static/img" # Media files will be stored in the repo under images/uploads

collections:
  # Our blog posts
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", default: "Taylor Barnett" }      
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Main Image", name: "main_image", widget: "image"}
  # Our pages e.g. About
  - name: "pages"
    label: "Page"
    folder: "pages"
    create: false # Change to true to allow editors to create new pages
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - { label: "Summary", name: "summary", widget: "text" }
      - label: "Navigation" # https://www.11ty.dev/docs/plugins/navigation/
        name: "eleventyNavigation"
        widget: "object"
        fields:
          - { label: "Key", name: "key", widget: "string" }
          - { label: "Order", name: "order", widget: "number", default: 0 }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Main Image", name: "main_image", widget: "image"}
  - name: "speaking"
    label: "Speaking"
    folder: "speaking"
    create: true # Change to true to allow editors to create new pages
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - label: "Featured Image"
        name: "featured_image"
        widget: "image"     
      - label: 'Future talks'
        name: 'future_talks'
        widget: 'list'
        fields:
          - { label: 'Talk name', name: 'talk_name', widget: 'string' }
          - { label: 'Conference name', name: 'conference_name', widget: 'string' }
          - { label: 'Conference URL', name: 'conference_url', widget: 'string' }
          - { label: 'Location', name: 'location', widget: 'string'}
          - { label: 'Date', name: 'date', widget: 'date' }        
      - { label: "Potential topics", name: "topics", widget: "markdown"}
      - label: 'Previous talks'
        name: 'previous_talks'
        widget: 'list'
        fields:
          - { label: 'Talk name', name: 'talk_name', widget: 'string' }
          - { label: 'Talk URL', name: 'talk_url', widget: 'string' }
          - { label: 'Conference name', name: 'conference_name', widget: 'string' }
          - { label: 'Conference URL', name: 'conference_url', widget: 'string' }
          - { label: 'Location', name: 'location', widget: 'string'}
          - { label: 'Date', name: 'date', widget: 'date' }
